#!groovy

// Generated by IBM TransformationAdvisor
// Thu Mar 12 19:36:13 UTC 2020

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'idswebapp'
    mvnCommands = '--version'
    test='false'
}